package org.bezsahara.kittybot.telegram.client

import io.vertx.core.http.HttpMethod
import io.vertx.core.http.RequestOptions


internal class TPath(
    val basePath: String,
    val token: String,
    val timeout: Long
) {
    @JvmField val deleteMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMessages").setMethod(HttpMethod.POST)
    @JvmField val setChatPhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatPhoto").setMethod(HttpMethod.POST)
    @JvmField val unpinAllGeneralForumTopicMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinAllGeneralForumTopicMessages").setMethod(HttpMethod.POST)
    @JvmField val editChatSubscriptionInviteLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editChatSubscriptionInviteLink").setMethod(HttpMethod.POST)
    @JvmField val deleteForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteForumTopic").setMethod(HttpMethod.POST)
    @JvmField val readBusinessMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/readBusinessMessage").setMethod(HttpMethod.POST)
    @JvmField val setChatPermissions: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatPermissions").setMethod(HttpMethod.POST)
    @JvmField val setMyProfilePhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val editMessageReplyMarkup: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageReplyMarkup").setMethod(HttpMethod.POST)
    @JvmField val banChatMember: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/banChatMember").setMethod(HttpMethod.POST)
    @JvmField val getBusinessAccountStarBalance: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getBusinessAccountStarBalance").setMethod(HttpMethod.POST)
    @JvmField val unhideGeneralForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unhideGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val verifyChat: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/verifyChat").setMethod(HttpMethod.POST)
    @JvmField val editStory: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editStory").setMethod(HttpMethod.POST)
    @JvmField val deleteChatPhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteChatPhoto").setMethod(HttpMethod.POST)
    @JvmField val copyMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/copyMessage").setMethod(HttpMethod.POST)
    @JvmField val reopenForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/reopenForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendDice: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendDice").setMethod(HttpMethod.POST)
    @JvmField val removeMyProfilePhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeMyProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val refundStarPayment: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/refundStarPayment").setMethod(HttpMethod.POST)
    @JvmField val getAvailableGifts: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getAvailableGifts").setMethod(HttpMethod.POST)
    @JvmField val sendLocation: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendLocation").setMethod(HttpMethod.POST)
    @JvmField val setChatAdministratorCustomTitle: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatAdministratorCustomTitle").setMethod(HttpMethod.POST)
    @JvmField val setUserEmojiStatus: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setUserEmojiStatus").setMethod(HttpMethod.POST)
    @JvmField val setChatTitle: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatTitle").setMethod(HttpMethod.POST)
    @JvmField val setChatDescription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatDescription").setMethod(HttpMethod.POST)
    @JvmField val getChatAdministrators: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatAdministrators").setMethod(HttpMethod.POST)
    @JvmField val getManagedBotToken: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getManagedBotToken").setMethod(HttpMethod.POST)
    @JvmField val getChatMemberCount: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatMemberCount").setMethod(HttpMethod.POST)
    @JvmField val removeUserVerification: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeUserVerification").setMethod(HttpMethod.POST)
    @JvmField val removeBusinessAccountProfilePhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeBusinessAccountProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val sendPhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendPhoto").setMethod(HttpMethod.POST)
    @JvmField val deleteMessageReaction: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMessageReaction").setMethod(HttpMethod.POST)
    @JvmField val sendSticker: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendSticker").setMethod(HttpMethod.POST)
    @JvmField val getUserProfileAudios: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserProfileAudios").setMethod(HttpMethod.POST)
    @JvmField val editMessageChecklist: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageChecklist").setMethod(HttpMethod.POST)
    @JvmField val setPassportDataErrors: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setPassportDataErrors").setMethod(HttpMethod.POST)
    @JvmField val setChatMenuButton: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatMenuButton").setMethod(HttpMethod.POST)
    @JvmField val hideGeneralForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/hideGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendPoll: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendPoll").setMethod(HttpMethod.POST)
    @JvmField val getChatMenuButton: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatMenuButton").setMethod(HttpMethod.POST)
    @JvmField val getUpdates: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUpdates").setMethod(HttpMethod.POST)
        .setTimeout(timeout * 1000)
    @JvmField val setMyName: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyName").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountName: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountName").setMethod(HttpMethod.POST)
    @JvmField val copyMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/copyMessages").setMethod(HttpMethod.POST)
    @JvmField val unpinChatMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinChatMessage").setMethod(HttpMethod.POST)
    @JvmField val stopMessageLiveLocation: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/stopMessageLiveLocation").setMethod(HttpMethod.POST)
    @JvmField val setStickerEmojiList: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerEmojiList").setMethod(HttpMethod.POST)
    @JvmField val getMyDescription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyDescription").setMethod(HttpMethod.POST)
    @JvmField val getChatMember: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatMember").setMethod(HttpMethod.POST)
    @JvmField val getUserProfilePhotos: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserProfilePhotos").setMethod(HttpMethod.POST)
    @JvmField val sendDocument: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendDocument").setMethod(HttpMethod.POST)
    @JvmField val createChatInviteLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val getStarTransactions: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getStarTransactions").setMethod(HttpMethod.POST)
    @JvmField val setChatStickerSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatStickerSet").setMethod(HttpMethod.POST)
    @JvmField val setMyShortDescription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyShortDescription").setMethod(HttpMethod.POST)
    @JvmField val uploadStickerFile: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/uploadStickerFile").setMethod(HttpMethod.POST)
    @JvmField val editChatInviteLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val leaveChat: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/leaveChat").setMethod(HttpMethod.POST)
    @JvmField val closeGeneralForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/closeGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val getManagedBotAccessSettings: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getManagedBotAccessSettings").setMethod(HttpMethod.POST)
    @JvmField val savePreparedKeyboardButton: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/savePreparedKeyboardButton").setMethod(HttpMethod.POST)
    @JvmField val setStickerSetThumbnail: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerSetThumbnail").setMethod(HttpMethod.POST)
    @JvmField val getMyDefaultAdministratorRights: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyDefaultAdministratorRights").setMethod(HttpMethod.POST)
    @JvmField val getMe: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMe").setMethod(HttpMethod.POST)
    @JvmField val setStickerPositionInSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerPositionInSet").setMethod(HttpMethod.POST)
    @JvmField val setCustomEmojiStickerSetThumbnail: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setCustomEmojiStickerSetThumbnail").setMethod(HttpMethod.POST)
    @JvmField val sendLivePhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendLivePhoto").setMethod(HttpMethod.POST)
    @JvmField val getUserPersonalChatMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserPersonalChatMessages").setMethod(HttpMethod.POST)
    @JvmField val close: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/close").setMethod(HttpMethod.POST)
    @JvmField val pinChatMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/pinChatMessage").setMethod(HttpMethod.POST)
    @JvmField val getCustomEmojiStickers: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getCustomEmojiStickers").setMethod(HttpMethod.POST)
    @JvmField val upgradeGift: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/upgradeGift").setMethod(HttpMethod.POST)
    @JvmField val answerInlineQuery: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerInlineQuery").setMethod(HttpMethod.POST)
    @JvmField val revokeChatInviteLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/revokeChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val transferBusinessAccountStars: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/transferBusinessAccountStars").setMethod(HttpMethod.POST)
    @JvmField val answerPreCheckoutQuery: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerPreCheckoutQuery").setMethod(HttpMethod.POST)
    @JvmField val sendMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendMessage").setMethod(HttpMethod.POST)
    @JvmField val sendChatAction: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendChatAction").setMethod(HttpMethod.POST)
    @JvmField val createChatSubscriptionInviteLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createChatSubscriptionInviteLink").setMethod(HttpMethod.POST)
    @JvmField val deleteMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMessage").setMethod(HttpMethod.POST)
    @JvmField val getMyShortDescription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyShortDescription").setMethod(HttpMethod.POST)
    @JvmField val answerShippingQuery: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerShippingQuery").setMethod(HttpMethod.POST)
    @JvmField val convertGiftToStars: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/convertGiftToStars").setMethod(HttpMethod.POST)
    @JvmField val savePreparedInlineMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/savePreparedInlineMessage").setMethod(HttpMethod.POST)
    @JvmField val deleteStory: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteStory").setMethod(HttpMethod.POST)
    @JvmField val setManagedBotAccessSettings: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setManagedBotAccessSettings").setMethod(HttpMethod.POST)
    @JvmField val giftPremiumSubscription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/giftPremiumSubscription").setMethod(HttpMethod.POST)
    @JvmField val editForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendContact: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendContact").setMethod(HttpMethod.POST)
    @JvmField val unpinAllChatMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinAllChatMessages").setMethod(HttpMethod.POST)
    @JvmField val restrictChatMember: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/restrictChatMember").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountProfilePhoto: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val getBusinessAccountGifts: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getBusinessAccountGifts").setMethod(HttpMethod.POST)
    @JvmField val forwardMessage: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/forwardMessage").setMethod(HttpMethod.POST)
    @JvmField val editUserStarSubscription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editUserStarSubscription").setMethod(HttpMethod.POST)
    @JvmField val getForumTopicIconStickers: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getForumTopicIconStickers").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountGiftSettings: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountGiftSettings").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountBio: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountBio").setMethod(HttpMethod.POST)
    @JvmField val unbanChatSenderChat: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unbanChatSenderChat").setMethod(HttpMethod.POST)
    @JvmField val getMyCommands: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyCommands").setMethod(HttpMethod.POST)
    @JvmField val setWebhook: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setWebhook").setMethod(HttpMethod.POST)
    @JvmField val setChatMemberTag: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatMemberTag").setMethod(HttpMethod.POST)
    @JvmField val setStickerMaskPosition: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerMaskPosition").setMethod(HttpMethod.POST)
    @JvmField val verifyUser: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/verifyUser").setMethod(HttpMethod.POST)
    @JvmField val deleteWebhook: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteWebhook").setMethod(HttpMethod.POST)
    @JvmField val sendGift: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendGift").setMethod(HttpMethod.POST)
    @JvmField val postStory: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/postStory").setMethod(HttpMethod.POST)
    @JvmField val getFile: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getFile").setMethod(HttpMethod.POST)
    @JvmField val transferGift: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/transferGift").setMethod(HttpMethod.POST)
    @JvmField val setStickerKeywords: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerKeywords").setMethod(HttpMethod.POST)
    @JvmField val getUserChatBoosts: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserChatBoosts").setMethod(HttpMethod.POST)
    @JvmField val getGameHighScores: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getGameHighScores").setMethod(HttpMethod.POST)
    @JvmField val createInvoiceLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createInvoiceLink").setMethod(HttpMethod.POST)
    @JvmField val reopenGeneralForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/reopenGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val deleteChatStickerSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteChatStickerSet").setMethod(HttpMethod.POST)
    @JvmField val editGeneralForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendVoice: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVoice").setMethod(HttpMethod.POST)
    @JvmField val banChatSenderChat: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/banChatSenderChat").setMethod(HttpMethod.POST)
    @JvmField val getWebhookInfo: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getWebhookInfo").setMethod(HttpMethod.POST)
    @JvmField val answerGuestQuery: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerGuestQuery").setMethod(HttpMethod.POST)
    @JvmField val setMyCommands: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyCommands").setMethod(HttpMethod.POST)
    @JvmField val editMessageText: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageText").setMethod(HttpMethod.POST)
    @JvmField val sendInvoice: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendInvoice").setMethod(HttpMethod.POST)
    @JvmField val getMyName: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyName").setMethod(HttpMethod.POST)
    @JvmField val setMessageReaction: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMessageReaction").setMethod(HttpMethod.POST)
    @JvmField val unbanChatMember: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unbanChatMember").setMethod(HttpMethod.POST)
    @JvmField val sendVideoNote: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVideoNote").setMethod(HttpMethod.POST)
    @JvmField val setMyDefaultAdministratorRights: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyDefaultAdministratorRights").setMethod(HttpMethod.POST)
    @JvmField val deleteAllMessageReactions: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteAllMessageReactions").setMethod(HttpMethod.POST)
    @JvmField val getChatGifts: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatGifts").setMethod(HttpMethod.POST)
    @JvmField val getChat: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChat").setMethod(HttpMethod.POST)
    @JvmField val deleteMyCommands: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMyCommands").setMethod(HttpMethod.POST)
    @JvmField val sendMessageDraft: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendMessageDraft").setMethod(HttpMethod.POST)
    @JvmField val createForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendMediaGroup: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendMediaGroup").setMethod(HttpMethod.POST)
    @JvmField val sendVideo: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVideo").setMethod(HttpMethod.POST)
    @JvmField val replaceManagedBotToken: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/replaceManagedBotToken").setMethod(HttpMethod.POST)
    @JvmField val promoteChatMember: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/promoteChatMember").setMethod(HttpMethod.POST)
    @JvmField val unpinAllForumTopicMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinAllForumTopicMessages").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountUsername: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountUsername").setMethod(HttpMethod.POST)
    @JvmField val setGameScore: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setGameScore").setMethod(HttpMethod.POST)
    @JvmField val sendPaidMedia: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendPaidMedia").setMethod(HttpMethod.POST)
    @JvmField val removeChatVerification: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeChatVerification").setMethod(HttpMethod.POST)
    @JvmField val getBusinessConnection: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getBusinessConnection").setMethod(HttpMethod.POST)
    @JvmField val sendGame: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendGame").setMethod(HttpMethod.POST)
    @JvmField val getUserGifts: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserGifts").setMethod(HttpMethod.POST)
    @JvmField val declineChatJoinRequest: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/declineChatJoinRequest").setMethod(HttpMethod.POST)
    @JvmField val sendVenue: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVenue").setMethod(HttpMethod.POST)
    @JvmField val stopPoll: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/stopPoll").setMethod(HttpMethod.POST)
    @JvmField val approveChatJoinRequest: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/approveChatJoinRequest").setMethod(HttpMethod.POST)
    @JvmField val sendAnimation: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendAnimation").setMethod(HttpMethod.POST)
    @JvmField val sendChecklist: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendChecklist").setMethod(HttpMethod.POST)
    @JvmField val declineSuggestedPost: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/declineSuggestedPost").setMethod(HttpMethod.POST)
    @JvmField val forwardMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/forwardMessages").setMethod(HttpMethod.POST)
    @JvmField val getStickerSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getStickerSet").setMethod(HttpMethod.POST)
    @JvmField val editMessageLiveLocation: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageLiveLocation").setMethod(HttpMethod.POST)
    @JvmField val sendAudio: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendAudio").setMethod(HttpMethod.POST)
    @JvmField val deleteStickerFromSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteStickerFromSet").setMethod(HttpMethod.POST)
    @JvmField val deleteBusinessMessages: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteBusinessMessages").setMethod(HttpMethod.POST)
    @JvmField val deleteStickerSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteStickerSet").setMethod(HttpMethod.POST)
    @JvmField val repostStory: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/repostStory").setMethod(HttpMethod.POST)
    @JvmField val answerWebAppQuery: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerWebAppQuery").setMethod(HttpMethod.POST)
    @JvmField val getMyStarBalance: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyStarBalance").setMethod(HttpMethod.POST)
    @JvmField val setStickerSetTitle: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerSetTitle").setMethod(HttpMethod.POST)
    @JvmField val exportChatInviteLink: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/exportChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val editMessageMedia: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageMedia").setMethod(HttpMethod.POST)
    @JvmField val closeForumTopic: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/closeForumTopic").setMethod(HttpMethod.POST)
    @JvmField val replaceStickerInSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/replaceStickerInSet").setMethod(HttpMethod.POST)
    @JvmField val answerCallbackQuery: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerCallbackQuery").setMethod(HttpMethod.POST)
    @JvmField val setMyDescription: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyDescription").setMethod(HttpMethod.POST)
    @JvmField val approveSuggestedPost: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/approveSuggestedPost").setMethod(HttpMethod.POST)
    @JvmField val addStickerToSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/addStickerToSet").setMethod(HttpMethod.POST)
    @JvmField val createNewStickerSet: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createNewStickerSet").setMethod(HttpMethod.POST)
    @JvmField val editMessageCaption: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageCaption").setMethod(HttpMethod.POST)
    @JvmField val logOut: RequestOptions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/logOut").setMethod(HttpMethod.POST)
}

