package org.bezsahara.kittybot.telegram.client

import io.vertx.core.http.HttpMethod
import io.vertx.core.http.RequestOptions


internal class TPath(
    val basePath: String,
    val token: String,
    val timeout: Long
) {
    @JvmField val deleteMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMessages").setMethod(HttpMethod.POST)
    @JvmField val setChatPhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatPhoto").setMethod(HttpMethod.POST)
    @JvmField val unpinAllGeneralForumTopicMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinAllGeneralForumTopicMessages").setMethod(HttpMethod.POST)
    @JvmField val editChatSubscriptionInviteLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editChatSubscriptionInviteLink").setMethod(HttpMethod.POST)
    @JvmField val deleteForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteForumTopic").setMethod(HttpMethod.POST)
    @JvmField val readBusinessMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/readBusinessMessage").setMethod(HttpMethod.POST)
    @JvmField val setChatPermissions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatPermissions").setMethod(HttpMethod.POST)
    @JvmField val setMyProfilePhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val editMessageReplyMarkup = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageReplyMarkup").setMethod(HttpMethod.POST)
    @JvmField val banChatMember = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/banChatMember").setMethod(HttpMethod.POST)
    @JvmField val getBusinessAccountStarBalance = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getBusinessAccountStarBalance").setMethod(HttpMethod.POST)
    @JvmField val unhideGeneralForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unhideGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val verifyChat = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/verifyChat").setMethod(HttpMethod.POST)
    @JvmField val editStory = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editStory").setMethod(HttpMethod.POST)
    @JvmField val deleteChatPhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteChatPhoto").setMethod(HttpMethod.POST)
    @JvmField val copyMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/copyMessage").setMethod(HttpMethod.POST)
    @JvmField val reopenForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/reopenForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendDice = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendDice").setMethod(HttpMethod.POST)
    @JvmField val removeMyProfilePhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeMyProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val refundStarPayment = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/refundStarPayment").setMethod(HttpMethod.POST)
    @JvmField val getAvailableGifts = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getAvailableGifts").setMethod(HttpMethod.POST)
    @JvmField val sendLocation = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendLocation").setMethod(HttpMethod.POST)
    @JvmField val setChatAdministratorCustomTitle = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatAdministratorCustomTitle").setMethod(HttpMethod.POST)
    @JvmField val setUserEmojiStatus = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setUserEmojiStatus").setMethod(HttpMethod.POST)
    @JvmField val setChatTitle = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatTitle").setMethod(HttpMethod.POST)
    @JvmField val sendRichMessageDraft = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendRichMessageDraft").setMethod(HttpMethod.POST)
    @JvmField val setChatDescription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatDescription").setMethod(HttpMethod.POST)
    @JvmField val getChatAdministrators = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatAdministrators").setMethod(HttpMethod.POST)
    @JvmField val getManagedBotToken = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getManagedBotToken").setMethod(HttpMethod.POST)
    @JvmField val getChatMemberCount = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatMemberCount").setMethod(HttpMethod.POST)
    @JvmField val removeUserVerification = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeUserVerification").setMethod(HttpMethod.POST)
    @JvmField val removeBusinessAccountProfilePhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeBusinessAccountProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val sendPhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendPhoto").setMethod(HttpMethod.POST)
    @JvmField val deleteMessageReaction = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMessageReaction").setMethod(HttpMethod.POST)
    @JvmField val sendSticker = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendSticker").setMethod(HttpMethod.POST)
    @JvmField val getUserProfileAudios = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserProfileAudios").setMethod(HttpMethod.POST)
    @JvmField val editMessageChecklist = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageChecklist").setMethod(HttpMethod.POST)
    @JvmField val setPassportDataErrors = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setPassportDataErrors").setMethod(HttpMethod.POST)
    @JvmField val setChatMenuButton = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatMenuButton").setMethod(HttpMethod.POST)
    @JvmField val hideGeneralForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/hideGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendPoll = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendPoll").setMethod(HttpMethod.POST)
    @JvmField val getChatMenuButton = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatMenuButton").setMethod(HttpMethod.POST)
    @JvmField val getUpdates = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUpdates").setMethod(HttpMethod.POST)
        .setTimeout(timeout * 1000)
    @JvmField val sendChatJoinRequestWebApp = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendChatJoinRequestWebApp").setMethod(HttpMethod.POST)
    @JvmField val setMyName = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyName").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountName = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountName").setMethod(HttpMethod.POST)
    @JvmField val copyMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/copyMessages").setMethod(HttpMethod.POST)
    @JvmField val unpinChatMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinChatMessage").setMethod(HttpMethod.POST)
    @JvmField val stopMessageLiveLocation = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/stopMessageLiveLocation").setMethod(HttpMethod.POST)
    @JvmField val setStickerEmojiList = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerEmojiList").setMethod(HttpMethod.POST)
    @JvmField val getMyDescription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyDescription").setMethod(HttpMethod.POST)
    @JvmField val getChatMember = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatMember").setMethod(HttpMethod.POST)
    @JvmField val getUserProfilePhotos = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserProfilePhotos").setMethod(HttpMethod.POST)
    @JvmField val sendDocument = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendDocument").setMethod(HttpMethod.POST)
    @JvmField val createChatInviteLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val getStarTransactions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getStarTransactions").setMethod(HttpMethod.POST)
    @JvmField val setChatStickerSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatStickerSet").setMethod(HttpMethod.POST)
    @JvmField val setMyShortDescription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyShortDescription").setMethod(HttpMethod.POST)
    @JvmField val uploadStickerFile = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/uploadStickerFile").setMethod(HttpMethod.POST)
    @JvmField val editChatInviteLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val leaveChat = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/leaveChat").setMethod(HttpMethod.POST)
    @JvmField val closeGeneralForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/closeGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val getManagedBotAccessSettings = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getManagedBotAccessSettings").setMethod(HttpMethod.POST)
    @JvmField val savePreparedKeyboardButton = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/savePreparedKeyboardButton").setMethod(HttpMethod.POST)
    @JvmField val setStickerSetThumbnail = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerSetThumbnail").setMethod(HttpMethod.POST)
    @JvmField val getMyDefaultAdministratorRights = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyDefaultAdministratorRights").setMethod(HttpMethod.POST)
    @JvmField val getMe = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMe").setMethod(HttpMethod.POST)
    @JvmField val setStickerPositionInSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerPositionInSet").setMethod(HttpMethod.POST)
    @JvmField val setCustomEmojiStickerSetThumbnail = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setCustomEmojiStickerSetThumbnail").setMethod(HttpMethod.POST)
    @JvmField val sendLivePhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendLivePhoto").setMethod(HttpMethod.POST)
    @JvmField val getUserPersonalChatMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserPersonalChatMessages").setMethod(HttpMethod.POST)
    @JvmField val close = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/close").setMethod(HttpMethod.POST)
    @JvmField val pinChatMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/pinChatMessage").setMethod(HttpMethod.POST)
    @JvmField val getCustomEmojiStickers = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getCustomEmojiStickers").setMethod(HttpMethod.POST)
    @JvmField val upgradeGift = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/upgradeGift").setMethod(HttpMethod.POST)
    @JvmField val answerInlineQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerInlineQuery").setMethod(HttpMethod.POST)
    @JvmField val revokeChatInviteLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/revokeChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val transferBusinessAccountStars = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/transferBusinessAccountStars").setMethod(HttpMethod.POST)
    @JvmField val answerPreCheckoutQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerPreCheckoutQuery").setMethod(HttpMethod.POST)
    @JvmField val sendMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendMessage").setMethod(HttpMethod.POST)
    @JvmField val sendChatAction = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendChatAction").setMethod(HttpMethod.POST)
    @JvmField val createChatSubscriptionInviteLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createChatSubscriptionInviteLink").setMethod(HttpMethod.POST)
    @JvmField val deleteMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMessage").setMethod(HttpMethod.POST)
    @JvmField val getMyShortDescription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyShortDescription").setMethod(HttpMethod.POST)
    @JvmField val answerShippingQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerShippingQuery").setMethod(HttpMethod.POST)
    @JvmField val convertGiftToStars = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/convertGiftToStars").setMethod(HttpMethod.POST)
    @JvmField val savePreparedInlineMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/savePreparedInlineMessage").setMethod(HttpMethod.POST)
    @JvmField val deleteStory = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteStory").setMethod(HttpMethod.POST)
    @JvmField val setManagedBotAccessSettings = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setManagedBotAccessSettings").setMethod(HttpMethod.POST)
    @JvmField val giftPremiumSubscription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/giftPremiumSubscription").setMethod(HttpMethod.POST)
    @JvmField val editForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendContact = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendContact").setMethod(HttpMethod.POST)
    @JvmField val unpinAllChatMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinAllChatMessages").setMethod(HttpMethod.POST)
    @JvmField val restrictChatMember = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/restrictChatMember").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountProfilePhoto = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountProfilePhoto").setMethod(HttpMethod.POST)
    @JvmField val getBusinessAccountGifts = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getBusinessAccountGifts").setMethod(HttpMethod.POST)
    @JvmField val forwardMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/forwardMessage").setMethod(HttpMethod.POST)
    @JvmField val editUserStarSubscription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editUserStarSubscription").setMethod(HttpMethod.POST)
    @JvmField val getForumTopicIconStickers = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getForumTopicIconStickers").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountGiftSettings = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountGiftSettings").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountBio = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountBio").setMethod(HttpMethod.POST)
    @JvmField val unbanChatSenderChat = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unbanChatSenderChat").setMethod(HttpMethod.POST)
    @JvmField val getMyCommands = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyCommands").setMethod(HttpMethod.POST)
    @JvmField val setWebhook = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setWebhook").setMethod(HttpMethod.POST)
    @JvmField val setChatMemberTag = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setChatMemberTag").setMethod(HttpMethod.POST)
    @JvmField val setStickerMaskPosition = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerMaskPosition").setMethod(HttpMethod.POST)
    @JvmField val verifyUser = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/verifyUser").setMethod(HttpMethod.POST)
    @JvmField val deleteWebhook = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteWebhook").setMethod(HttpMethod.POST)
    @JvmField val sendGift = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendGift").setMethod(HttpMethod.POST)
    @JvmField val postStory = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/postStory").setMethod(HttpMethod.POST)
    @JvmField val getFile = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getFile").setMethod(HttpMethod.POST)
    @JvmField val transferGift = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/transferGift").setMethod(HttpMethod.POST)
    @JvmField val setStickerKeywords = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerKeywords").setMethod(HttpMethod.POST)
    @JvmField val getUserChatBoosts = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserChatBoosts").setMethod(HttpMethod.POST)
    @JvmField val getGameHighScores = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getGameHighScores").setMethod(HttpMethod.POST)
    @JvmField val createInvoiceLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createInvoiceLink").setMethod(HttpMethod.POST)
    @JvmField val reopenGeneralForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/reopenGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val deleteChatStickerSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteChatStickerSet").setMethod(HttpMethod.POST)
    @JvmField val editGeneralForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editGeneralForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendVoice = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVoice").setMethod(HttpMethod.POST)
    @JvmField val banChatSenderChat = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/banChatSenderChat").setMethod(HttpMethod.POST)
    @JvmField val getWebhookInfo = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getWebhookInfo").setMethod(HttpMethod.POST)
    @JvmField val answerGuestQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerGuestQuery").setMethod(HttpMethod.POST)
    @JvmField val setMyCommands = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyCommands").setMethod(HttpMethod.POST)
    @JvmField val editMessageText = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageText").setMethod(HttpMethod.POST)
    @JvmField val sendInvoice = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendInvoice").setMethod(HttpMethod.POST)
    @JvmField val getMyName = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyName").setMethod(HttpMethod.POST)
    @JvmField val setMessageReaction = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMessageReaction").setMethod(HttpMethod.POST)
    @JvmField val unbanChatMember = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unbanChatMember").setMethod(HttpMethod.POST)
    @JvmField val sendVideoNote = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVideoNote").setMethod(HttpMethod.POST)
    @JvmField val setMyDefaultAdministratorRights = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyDefaultAdministratorRights").setMethod(HttpMethod.POST)
    @JvmField val deleteAllMessageReactions = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteAllMessageReactions").setMethod(HttpMethod.POST)
    @JvmField val getChatGifts = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChatGifts").setMethod(HttpMethod.POST)
    @JvmField val getChat = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getChat").setMethod(HttpMethod.POST)
    @JvmField val deleteMyCommands = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteMyCommands").setMethod(HttpMethod.POST)
    @JvmField val sendMessageDraft = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendMessageDraft").setMethod(HttpMethod.POST)
    @JvmField val createForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createForumTopic").setMethod(HttpMethod.POST)
    @JvmField val sendMediaGroup = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendMediaGroup").setMethod(HttpMethod.POST)
    @JvmField val sendVideo = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVideo").setMethod(HttpMethod.POST)
    @JvmField val replaceManagedBotToken = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/replaceManagedBotToken").setMethod(HttpMethod.POST)
    @JvmField val promoteChatMember = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/promoteChatMember").setMethod(HttpMethod.POST)
    @JvmField val unpinAllForumTopicMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/unpinAllForumTopicMessages").setMethod(HttpMethod.POST)
    @JvmField val setBusinessAccountUsername = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setBusinessAccountUsername").setMethod(HttpMethod.POST)
    @JvmField val setGameScore = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setGameScore").setMethod(HttpMethod.POST)
    @JvmField val answerChatJoinRequestQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerChatJoinRequestQuery").setMethod(HttpMethod.POST)
    @JvmField val sendPaidMedia = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendPaidMedia").setMethod(HttpMethod.POST)
    @JvmField val removeChatVerification = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/removeChatVerification").setMethod(HttpMethod.POST)
    @JvmField val getBusinessConnection = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getBusinessConnection").setMethod(HttpMethod.POST)
    @JvmField val sendGame = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendGame").setMethod(HttpMethod.POST)
    @JvmField val getUserGifts = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getUserGifts").setMethod(HttpMethod.POST)
    @JvmField val declineChatJoinRequest = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/declineChatJoinRequest").setMethod(HttpMethod.POST)
    @JvmField val sendVenue = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendVenue").setMethod(HttpMethod.POST)
    @JvmField val stopPoll = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/stopPoll").setMethod(HttpMethod.POST)
    @JvmField val approveChatJoinRequest = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/approveChatJoinRequest").setMethod(HttpMethod.POST)
    @JvmField val sendAnimation = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendAnimation").setMethod(HttpMethod.POST)
    @JvmField val sendChecklist = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendChecklist").setMethod(HttpMethod.POST)
    @JvmField val declineSuggestedPost = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/declineSuggestedPost").setMethod(HttpMethod.POST)
    @JvmField val forwardMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/forwardMessages").setMethod(HttpMethod.POST)
    @JvmField val getStickerSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getStickerSet").setMethod(HttpMethod.POST)
    @JvmField val sendRichMessage = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendRichMessage").setMethod(HttpMethod.POST)
    @JvmField val editMessageLiveLocation = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageLiveLocation").setMethod(HttpMethod.POST)
    @JvmField val sendAudio = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/sendAudio").setMethod(HttpMethod.POST)
    @JvmField val deleteStickerFromSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteStickerFromSet").setMethod(HttpMethod.POST)
    @JvmField val deleteBusinessMessages = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteBusinessMessages").setMethod(HttpMethod.POST)
    @JvmField val deleteStickerSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/deleteStickerSet").setMethod(HttpMethod.POST)
    @JvmField val repostStory = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/repostStory").setMethod(HttpMethod.POST)
    @JvmField val answerWebAppQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerWebAppQuery").setMethod(HttpMethod.POST)
    @JvmField val getMyStarBalance = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/getMyStarBalance").setMethod(HttpMethod.POST)
    @JvmField val setStickerSetTitle = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setStickerSetTitle").setMethod(HttpMethod.POST)
    @JvmField val exportChatInviteLink = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/exportChatInviteLink").setMethod(HttpMethod.POST)
    @JvmField val editMessageMedia = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageMedia").setMethod(HttpMethod.POST)
    @JvmField val closeForumTopic = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/closeForumTopic").setMethod(HttpMethod.POST)
    @JvmField val replaceStickerInSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/replaceStickerInSet").setMethod(HttpMethod.POST)
    @JvmField val answerCallbackQuery = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/answerCallbackQuery").setMethod(HttpMethod.POST)
    @JvmField val setMyDescription = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/setMyDescription").setMethod(HttpMethod.POST)
    @JvmField val approveSuggestedPost = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/approveSuggestedPost").setMethod(HttpMethod.POST)
    @JvmField val addStickerToSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/addStickerToSet").setMethod(HttpMethod.POST)
    @JvmField val createNewStickerSet = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/createNewStickerSet").setMethod(HttpMethod.POST)
    @JvmField val editMessageCaption = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/editMessageCaption").setMethod(HttpMethod.POST)
    @JvmField val logOut = RequestOptions()
        .putHeader("Content-Type", "application/json").setAbsoluteURI("$basePath/logOut").setMethod(HttpMethod.POST)
}

